" preferences
" encoding
set encoding=utf-8
set fileencoding=utf-8
scriptencoding utf-8
" lang
let $LANG='en_US.UTF-8'
set helplang=ja,en
" .viminfo path
set viminfo+=n~/.vim/viminfo
" line number
set number
" highlight current line
set cursorline
" cursor position
set ruler
" sign
set signcolumn=yes
" invisible character
set list
set listchars=tab:▸-,trail:⋅,nbsp:␣,extends:❯,precedes:❮
" status line
set laststatus=3
" gui setting
set guifont=GohuFont\ Nerd\ Font,PlemolJP\ Console\ NF
set guifontwide=GohuFont\ Nerd\ Font,PlemolJP\ Console\ NF
set termguicolors
set mouse-=a
set guicursor+=i:block,a:-blinkwait175-blinkoff150-blinkon175
" search
set hlsearch
set ignorecase
set smartcase
set incsearch
set noignorecase
set nowrapscan
" command history
set history=1000
" complement
set wildmenu
set completeopt=menuone,noinsert
" indent
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
" window split
set splitbelow
set splitright
" syntax highlight
syntax enable
" disable intro
set shortmess=I
set clipboard+=unnamedplus
" hide highlight search
nnoremap <ESC><ESC> :nohlsearch<CR>
" wsl
if !empty($WSL_DISTRO_NAME)
    " clipboard sharing
    let s:clip = '/mnt/c/Windows/System32/clip.exe'
    if executable(s:clip)
        augroup WSLYank
            autocmd!
            autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
        augroup END
    endif
    " ime off when leave insert mode
    if executable('spzenhan.exe')
        autocmd InsertLeave * :call system('spzenhan.exe 0')
        autocmd CmdlineLeave * :call system('spzenhan.exe 0')
    endif
endif
" plugin
call plug#begin()
    " colorscheme
    Plug 'arcticicestudio/nord-vim'
    " clipboard history
    Plug 'vim-scripts/YankRing.vim'
    " ime off when leave insert mode
    Plug 'kaz399/spzenhan.vim'
call plug#end()
" colorscheme
colorscheme nord
" yankRing
let g:yankring_history_dir = '$XDG_STATE_HOME/yankring'
