return {
  {
    -- https://github.com/williamboman/mason-lspconfig.nvim
    'williamboman/mason-lspconfig.nvim',
    opts = {
      ensure_installed = {
        'angularls',
        'arduino_language_server',
        'asm_lsp',
        'astro',
        'awk_ls',
        'bashls',
        'clangd',
        'cssls',
        'denols',
        'diagnosticls',
        'docker_compose_language_service',
        'dockerls',
        'elmls',
        'eslint',
        'gopls',
        'gradle_ls',
        'html',
        'intelephense',
        'jedi_language_server',
        'jsonls',
        'jdtls',
        'kotlin_language_server',
        'lua_ls',
        'marksman',
        'neocmake',
        'omnisharp_mono',
        'perlnavigator',
        'powershell_es',
        'rust_analyzer',
        'spectral',
        'sqlls',
        'tailwindcss',
        'taplo',
        'terraformls',
        'tsserver',
        'volar',
        'lemminx',
        'yamlls',
      },
      automatic_installation = true,
    },
  },
}
