-- keymaps
---- curor move
------ ctrl + left (move to begin of the word)
hs.hotkey.bind({ "ctrl" }, "left", nil, function()
  hs.eventtap.keyStroke({ "option" }, "left")
end, function()
  hs.eventtap.keyStroke({ "option" }, "left")
end)
------ ctrl + shift + left (move to begin of the word with selection)
hs.hotkey.bind({ "ctrl", "shift" }, "left", nil, function()
  hs.eventtap.keyStroke({ "option", "shift" }, "left")
end, function()
  hs.eventtap.keyStroke({ "option", "shift" }, "left")
end)
------ ctrl + right (move to end of the word)
hs.hotkey.bind({ "ctrl" }, "right", nil, function()
  hs.eventtap.keyStroke({ "option" }, "right")
end, function()
  hs.eventtap.keyStroke({ "option" }, "right")
end)
------ ctrl + shift + right (move to end of the word with selection)
hs.hotkey.bind({ "ctrl", "shift" }, "right", nil, function()
  hs.eventtap.keyStroke({ "option", "shift" }, "right")
end, function()
  hs.eventtap.keyStroke({ "option", "shift" }, "right")
end)
---- quit
hs.hotkey.bind({ "option" }, "f4", nil, function()
  hs.eventtap.keyStroke({ "cmd" }, "q")
end)
